# Generated by Django 3.2.16 on 2022-12-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20221207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
