# Generated by Django 3.2.16 on 2022-12-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_taskrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
