# Generated by Django 3.2.16 on 2022-12-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_taskrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '校验中'), (2, '编译中'), (3, '打包中'), (4, '完成'), (5, '校验失败'), (6, '编译失败'), (7, '打包失败')], default=0, max_length=2),
        ),
    ]
