# Generated by Django 3.2.16 on 2022-12-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_alter_taskrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '校验中'), (3, '编译中'), (5, '打包中'), (6, '完成'), (2, '校验完成'), (4, '编译完成'), (7, '校验失败'), (8, '编译失败'), (9, '打包失败')], default=0, max_length=2),
        ),
    ]
