# Generated by Django 3.2.16 on 2022-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_alter_taskrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='err_msg',
            field=models.TextField(blank=True, null=True, verbose_name='error'),
        ),
    ]
